// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_lvl5 = new UnifiedAchievement("Lvl5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQMQ"
#else
            "Lvl5"
#endif
            );

        public static UnifiedAchievement Lvl5
        {
            get { return s_lvl5; }
        }

        private static readonly UnifiedAchievement s_lvl10 = new UnifiedAchievement("Lvl10",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQMg"
#else
            "Lvl10"
#endif
            );

        public static UnifiedAchievement Lvl10
        {
            get { return s_lvl10; }
        }

        private static readonly UnifiedAchievement s_lvl15 = new UnifiedAchievement("Lvl15",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQMw"
#else
            "Lvl15"
#endif
            );

        public static UnifiedAchievement Lvl15
        {
            get { return s_lvl15; }
        }

        private static readonly UnifiedAchievement s_lvl20 = new UnifiedAchievement("Lvl20",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQNA"
#else
            "Lvl20"
#endif
            );

        public static UnifiedAchievement Lvl20
        {
            get { return s_lvl20; }
        }

        private static readonly UnifiedAchievement s_lvl25 = new UnifiedAchievement("Lvl25",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQNQ"
#else
            "Lvl25"
#endif
            );

        public static UnifiedAchievement Lvl25
        {
            get { return s_lvl25; }
        }

        private static readonly UnifiedAchievement s_lvl30 = new UnifiedAchievement("Lvl30",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQNg"
#else
            "Lvl30"
#endif
            );

        public static UnifiedAchievement Lvl30
        {
            get { return s_lvl30; }
        }

        private static readonly UnifiedAchievement s_lvl5wu = new UnifiedAchievement("Lvl5wu",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "385269171465"
#else
            "Lvl5wu"
#endif
            );

        public static UnifiedAchievement Lvl5wu
        {
            get { return s_lvl5wu; }
        }

        private static readonly UnifiedAchievement s_lvl10wu = new UnifiedAchievement("Lvl10wu",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQOA"
#else
            "Lvl10wu"
#endif
            );

        public static UnifiedAchievement Lvl10wu
        {
            get { return s_lvl10wu; }
        }

        private static readonly UnifiedAchievement s_lvl15wu = new UnifiedAchievement("Lvl15wu",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQOQ"
#else
            "Lvl15wu"
#endif
            );

        public static UnifiedAchievement Lvl15wu
        {
            get { return s_lvl15wu; }
        }

        private static readonly UnifiedAchievement s_lvl20wu = new UnifiedAchievement("Lvl20wu",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQOg"
#else
            "Lvl20wu"
#endif
            );

        public static UnifiedAchievement Lvl20wu
        {
            get { return s_lvl20wu; }
        }

        private static readonly UnifiedAchievement s_lvl25wu = new UnifiedAchievement("Lvl25wu",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQOw"
#else
            "Lvl25wu"
#endif
            );

        public static UnifiedAchievement Lvl25wu
        {
            get { return s_lvl25wu; }
        }

        private static readonly UnifiedAchievement s_lvl30wu = new UnifiedAchievement("Lvl30wu",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQPA"
#else
            "Lvl30wu"
#endif
            );

        public static UnifiedAchievement Lvl30wu
        {
            get { return s_lvl30wu; }
        }

        private static readonly UnifiedAchievement s_lvl5wd = new UnifiedAchievement("Lvl5wd",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQPQ"
#else
            "Lvl5wd"
#endif
            );

        public static UnifiedAchievement Lvl5wd
        {
            get { return s_lvl5wd; }
        }

        private static readonly UnifiedAchievement s_lvl10wd = new UnifiedAchievement("Lvl10wd",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQPg"
#else
            "Lvl10wd"
#endif
            );

        public static UnifiedAchievement Lvl10wd
        {
            get { return s_lvl10wd; }
        }

        private static readonly UnifiedAchievement s_lvl15wd = new UnifiedAchievement("Lvl15wd",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQPw"
#else
            "Lvl15wd"
#endif
            );

        public static UnifiedAchievement Lvl15wd
        {
            get { return s_lvl15wd; }
        }

        private static readonly UnifiedAchievement s_lvl20wd = new UnifiedAchievement("Lvl20wd",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQQA"
#else
            "Lvl20wd"
#endif
            );

        public static UnifiedAchievement Lvl20wd
        {
            get { return s_lvl20wd; }
        }

        private static readonly UnifiedAchievement s_lvl25wd = new UnifiedAchievement("Lvl25wd",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQQQ"
#else
            "Lvl25wd"
#endif
            );

        public static UnifiedAchievement Lvl25wd
        {
            get { return s_lvl25wd; }
        }

        private static readonly UnifiedAchievement s_lvl30wd = new UnifiedAchievement("Lvl30wd",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQQg"
#else
            "Lvl30wd"
#endif
            );

        public static UnifiedAchievement Lvl30wd
        {
            get { return s_lvl30wd; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_lvl5,
            s_lvl10,
            s_lvl15,
            s_lvl20,
            s_lvl25,
            s_lvl30,
            s_lvl5wu,
            s_lvl10wu,
            s_lvl15wu,
            s_lvl20wu,
            s_lvl25wu,
            s_lvl30wu,
            s_lvl5wd,
            s_lvl10wd,
            s_lvl15wd,
            s_lvl20wd,
            s_lvl25wd,
            s_lvl30wd,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "Lvl5", s_lvl5 },
            { "Lvl10", s_lvl10 },
            { "Lvl15", s_lvl15 },
            { "Lvl20", s_lvl20 },
            { "Lvl25", s_lvl25 },
            { "Lvl30", s_lvl30 },
            { "Lvl5wu", s_lvl5wu },
            { "Lvl10wu", s_lvl10wu },
            { "Lvl15wu", s_lvl15wu },
            { "Lvl20wu", s_lvl20wu },
            { "Lvl25wu", s_lvl25wu },
            { "Lvl30wu", s_lvl30wu },
            { "Lvl5wd", s_lvl5wd },
            { "Lvl10wd", s_lvl10wd },
            { "Lvl15wd", s_lvl15wd },
            { "Lvl20wd", s_lvl20wd },
            { "Lvl25wd", s_lvl25wd },
            { "Lvl30wd", s_lvl30wd },
        };
    }
}
