// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_lvl1 = new UnifiedLeaderboard("Lvl1",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQKg"
#else
            "Lvl1"
#endif
            );

        public static UnifiedLeaderboard Lvl1
        {
            get { return s_lvl1; }
        }

        private static readonly UnifiedLeaderboard s_lvl2 = new UnifiedLeaderboard("Lvl2",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQKw"
#else
            "Lvl2"
#endif
            );

        public static UnifiedLeaderboard Lvl2
        {
            get { return s_lvl2; }
        }

        private static readonly UnifiedLeaderboard s_lvl3 = new UnifiedLeaderboard("Lvl3",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQLA"
#else
            "Lvl3"
#endif
            );

        public static UnifiedLeaderboard Lvl3
        {
            get { return s_lvl3; }
        }

        private static readonly UnifiedLeaderboard s_lvl4 = new UnifiedLeaderboard("Lvl4",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQLQ"
#else
            "Lvl4"
#endif
            );

        public static UnifiedLeaderboard Lvl4
        {
            get { return s_lvl4; }
        }

        private static readonly UnifiedLeaderboard s_lvl5 = new UnifiedLeaderboard("Lvl5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQLg"
#else
            "Lvl5"
#endif
            );

        public static UnifiedLeaderboard Lvl5
        {
            get { return s_lvl5; }
        }

        private static readonly UnifiedLeaderboard s_lvl6 = new UnifiedLeaderboard("Lvl6",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQLw"
#else
            "Lvl6"
#endif
            );

        public static UnifiedLeaderboard Lvl6
        {
            get { return s_lvl6; }
        }

        private static readonly UnifiedLeaderboard s_lvl7 = new UnifiedLeaderboard("Lvl7",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQMA"
#else
            "Lvl7"
#endif
            );

        public static UnifiedLeaderboard Lvl7
        {
            get { return s_lvl7; }
        }

        private static readonly UnifiedLeaderboard s_lvl8 = new UnifiedLeaderboard("Lvl8",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQEg"
#else
            "Lvl8"
#endif
            );

        public static UnifiedLeaderboard Lvl8
        {
            get { return s_lvl8; }
        }

        private static readonly UnifiedLeaderboard s_lvl9 = new UnifiedLeaderboard("Lvl9",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQEw"
#else
            "Lvl9"
#endif
            );

        public static UnifiedLeaderboard Lvl9
        {
            get { return s_lvl9; }
        }

        private static readonly UnifiedLeaderboard s_lvl10 = new UnifiedLeaderboard("Lvl10",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQFA"
#else
            "Lvl10"
#endif
            );

        public static UnifiedLeaderboard Lvl10
        {
            get { return s_lvl10; }
        }

        private static readonly UnifiedLeaderboard s_lvl11 = new UnifiedLeaderboard("Lvl11",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQFQ"
#else
            "Lvl11"
#endif
            );

        public static UnifiedLeaderboard Lvl11
        {
            get { return s_lvl11; }
        }

        private static readonly UnifiedLeaderboard s_lvl12 = new UnifiedLeaderboard("Lvl12",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQFg"
#else
            "Lvl12"
#endif
            );

        public static UnifiedLeaderboard Lvl12
        {
            get { return s_lvl12; }
        }

        private static readonly UnifiedLeaderboard s_lvl13 = new UnifiedLeaderboard("Lvl13",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQFw"
#else
            "Lvl13"
#endif
            );

        public static UnifiedLeaderboard Lvl13
        {
            get { return s_lvl13; }
        }

        private static readonly UnifiedLeaderboard s_lvl14 = new UnifiedLeaderboard("Lvl14",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQGA"
#else
            "Lvl14"
#endif
            );

        public static UnifiedLeaderboard Lvl14
        {
            get { return s_lvl14; }
        }

        private static readonly UnifiedLeaderboard s_lvl15 = new UnifiedLeaderboard("Lvl15",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQGQ"
#else
            "Lvl15"
#endif
            );

        public static UnifiedLeaderboard Lvl15
        {
            get { return s_lvl15; }
        }

        private static readonly UnifiedLeaderboard s_lvl16 = new UnifiedLeaderboard("Lvl16",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQGg"
#else
            "Lvl16"
#endif
            );

        public static UnifiedLeaderboard Lvl16
        {
            get { return s_lvl16; }
        }

        private static readonly UnifiedLeaderboard s_lvl17 = new UnifiedLeaderboard("Lvl17",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQGw"
#else
            "Lvl17"
#endif
            );

        public static UnifiedLeaderboard Lvl17
        {
            get { return s_lvl17; }
        }

        private static readonly UnifiedLeaderboard s_lvl18 = new UnifiedLeaderboard("Lvl18",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQHA"
#else
            "Lvl18"
#endif
            );

        public static UnifiedLeaderboard Lvl18
        {
            get { return s_lvl18; }
        }

        private static readonly UnifiedLeaderboard s_lvl19 = new UnifiedLeaderboard("Lvl19",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQHQ"
#else
            "Lvl19"
#endif
            );

        public static UnifiedLeaderboard Lvl19
        {
            get { return s_lvl19; }
        }

        private static readonly UnifiedLeaderboard s_lvl20 = new UnifiedLeaderboard("Lvl20",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQHg"
#else
            "Lvl20"
#endif
            );

        public static UnifiedLeaderboard Lvl20
        {
            get { return s_lvl20; }
        }

        private static readonly UnifiedLeaderboard s_lvl21 = new UnifiedLeaderboard("Lvl21",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQHw"
#else
            "Lvl21"
#endif
            );

        public static UnifiedLeaderboard Lvl21
        {
            get { return s_lvl21; }
        }

        private static readonly UnifiedLeaderboard s_lvl22 = new UnifiedLeaderboard("Lvl22",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQIA"
#else
            "Lvl22"
#endif
            );

        public static UnifiedLeaderboard Lvl22
        {
            get { return s_lvl22; }
        }

        private static readonly UnifiedLeaderboard s_lvl23 = new UnifiedLeaderboard("Lvl23",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQIQ"
#else
            "Lvl23"
#endif
            );

        public static UnifiedLeaderboard Lvl23
        {
            get { return s_lvl23; }
        }

        private static readonly UnifiedLeaderboard s_lvl24 = new UnifiedLeaderboard("Lvl24",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQIg"
#else
            "Lvl24"
#endif
            );

        public static UnifiedLeaderboard Lvl24
        {
            get { return s_lvl24; }
        }

        private static readonly UnifiedLeaderboard s_lvl25 = new UnifiedLeaderboard("Lvl25",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQIw"
#else
            "Lvl25"
#endif
            );

        public static UnifiedLeaderboard Lvl25
        {
            get { return s_lvl25; }
        }

        private static readonly UnifiedLeaderboard s_lvl26 = new UnifiedLeaderboard("Lvl26",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQJA"
#else
            "Lvl26"
#endif
            );

        public static UnifiedLeaderboard Lvl26
        {
            get { return s_lvl26; }
        }

        private static readonly UnifiedLeaderboard s_lvl27 = new UnifiedLeaderboard("Lvl27",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQJQ"
#else
            "Lvl27"
#endif
            );

        public static UnifiedLeaderboard Lvl27
        {
            get { return s_lvl27; }
        }

        private static readonly UnifiedLeaderboard s_lvl28 = new UnifiedLeaderboard("Lvl28",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQJg"
#else
            "Lvl28"
#endif
            );

        public static UnifiedLeaderboard Lvl28
        {
            get { return s_lvl28; }
        }

        private static readonly UnifiedLeaderboard s_lvl29 = new UnifiedLeaderboard("Lvl29",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQJw"
#else
            "Lvl29"
#endif
            );

        public static UnifiedLeaderboard Lvl29
        {
            get { return s_lvl29; }
        }

        private static readonly UnifiedLeaderboard s_lvl30 = new UnifiedLeaderboard("Lvl30",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIiYrUnpsLEAIQKA"
#else
            "Lvl30"
#endif
            );

        public static UnifiedLeaderboard Lvl30
        {
            get { return s_lvl30; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "Lvl1", s_lvl1 },
            { "Lvl2", s_lvl2 },
            { "Lvl3", s_lvl3 },
            { "Lvl4", s_lvl4 },
            { "Lvl5", s_lvl5 },
            { "Lvl6", s_lvl6 },
            { "Lvl7", s_lvl7 },
            { "Lvl8", s_lvl8 },
            { "Lvl9", s_lvl9 },
            { "Lvl10", s_lvl10 },
            { "Lvl11", s_lvl11 },
            { "Lvl12", s_lvl12 },
            { "Lvl13", s_lvl13 },
            { "Lvl14", s_lvl14 },
            { "Lvl15", s_lvl15 },
            { "Lvl16", s_lvl16 },
            { "Lvl17", s_lvl17 },
            { "Lvl18", s_lvl18 },
            { "Lvl19", s_lvl19 },
            { "Lvl20", s_lvl20 },
            { "Lvl21", s_lvl21 },
            { "Lvl22", s_lvl22 },
            { "Lvl23", s_lvl23 },
            { "Lvl24", s_lvl24 },
            { "Lvl25", s_lvl25 },
            { "Lvl26", s_lvl26 },
            { "Lvl27", s_lvl27 },
            { "Lvl28", s_lvl28 },
            { "Lvl29", s_lvl29 },
            { "Lvl30", s_lvl30 },
        };
    }
}
